"""added movie title unique true

Revision ID: 034ef055efc5
Revises: 293dcf8e963e
Create Date: 2025-02-23 19:26:26.221162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '034ef055efc5'
down_revision: Union[str, None] = '293dcf8e963e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movies_title', table_name='movies')
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.create_index('ix_movies_title', 'movies', ['title'], unique=False)
    # ### end Alembic commands ###
