"""added activated bool field in product model

Revision ID: 0482bb7c7ee7
Revises: 712622d81fb1
Create Date: 2025-02-16 14:09:16.579349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0482bb7c7ee7'
down_revision: Union[str, None] = '712622d81fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('activated', sa.Boolean(), nullable=False, server_default=sa.text("TRUE")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'activated')
    # ### end Alembic commands ###
