"""added cascade for user entity relations

Revision ID: 21309bb22026
Revises: d949fb1c6103
Create Date: 2025-02-13 14:55:20.323011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21309bb22026'
down_revision: Union[str, None] = 'd949fb1c6103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('entities_creator_id_key', 'entities', type_='unique')
    op.drop_constraint('entities_creator_id_fkey', 'entities', type_='foreignkey')
    op.drop_column('entities', 'creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('entities_creator_id_fkey', 'entities', 'users', ['creator_id'], ['id'])
    op.create_unique_constraint('entities_creator_id_key', 'entities', ['creator_id'])
    # ### end Alembic commands ###
