"""added Index to activated field in product model

Revision ID: 4e578303fba9
Revises: 0482bb7c7ee7
Create Date: 2025-02-16 14:23:05.662213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e578303fba9'
down_revision: Union[str, None] = '0482bb7c7ee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_products_activated'), 'products', ['activated'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_activated'), table_name='products')
    # ### end Alembic commands ###
