"""vectorized ProductModel and Unique constrain owner-product_name

Revision ID: 51d190df5d7b
Revises: 339d24aa0831
Create Date: 2025-02-15 12:52:26.573032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51d190df5d7b'
down_revision: Union[str, None] = '339d24aa0831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.create_index('idx_products_search', 'products', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_unique_constraint('uix_owner_product_name', 'products', ['name', 'owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_owner_product_name', 'products', type_='unique')
    op.drop_index('idx_products_search', table_name='products', postgresql_using='gin')
    op.drop_column('products', 'search_vector')
    # ### end Alembic commands ###
