"""corrected entity whatsapp

Revision ID: 66336c7b8e55
Revises: 9adc46fb3b35
Create Date: 2025-02-13 00:51:57.945752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66336c7b8e55'
down_revision: Union[str, None] = '9adc46fb3b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('entity_whatsapp', sa.String(length=20), nullable=False))
    op.drop_constraint('entities_entity_whapsapp_key', 'entities', type_='unique')
    op.create_unique_constraint(None, 'entities', ['entity_whatsapp'])
    op.drop_column('entities', 'entity_whapsapp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('entity_whapsapp', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'entities', type_='unique')
    op.create_unique_constraint('entities_entity_whapsapp_key', 'entities', ['entity_whapsapp'])
    op.drop_column('entities', 'entity_whatsapp')
    # ### end Alembic commands ###
