"""added CREATOR Enum for UserModel

Revision ID: 6900aa23a1cd
Revises: 564812197d61
Create Date: 2025-02-28 11:56:36.476088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6900aa23a1cd'
down_revision: Union[str, None] = '564812197d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
