"""added Orders FK to UsersModel

Revision ID: 6e53b6532680
Revises: 72f4c6a41630
Create Date: 2025-02-27 15:11:22.943852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e53b6532680'
down_revision: Union[str, None] = '72f4c6a41630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
