"""added is_dollar to ProductDTO

Revision ID: 712622d81fb1
Revises: a6d1adcdb31c
Create Date: 2025-02-15 21:32:21.445058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '712622d81fb1'
down_revision: Union[str, None] = 'a6d1adcdb31c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
