"""added is_dollar to ProductModel, dtos

Revision ID: a6d1adcdb31c
Revises: 5ab9069f29a1
Create Date: 2025-02-15 21:23:18.702668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6d1adcdb31c'
down_revision: Union[str, None] = '5ab9069f29a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("is_dollar", sa.Boolean(), nullable=True))  # Make it temporarily nullable
    op.execute("UPDATE products SET is_dollar = FALSE")  # Assign default value to existing rows
    op.alter_column("products", "is_dollar", nullable=False)  # Enforce NOT NULL constraint

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_dollar')
    # ### end Alembic commands ###
