"""added cascade for user entity relations

Revision ID: b58b0de72b37
Revises: 21309bb22026
Create Date: 2025-02-13 15:00:04.853153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b58b0de72b37'
down_revision: Union[str, None] = '21309bb22026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'entities', ['creator_id'])
    op.create_foreign_key(None, 'entities', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entities', type_='foreignkey')
    op.drop_constraint(None, 'entities', type_='unique')
    op.drop_column('entities', 'creator_id')
    # ### end Alembic commands ###
