"""vectorized ProductModel for exact search

Revision ID: bfd865d40efc
Revises: 51d190df5d7b
Create Date: 2025-02-15 13:35:10.359843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd865d40efc'
down_revision: Union[str, None] = '51d190df5d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_products_exact_match', 'products', ['name', 'description', 'category'], unique=False, postgresql_using='btree')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_products_exact_match', table_name='products', postgresql_using='btree')
    # ### end Alembic commands ###
